services:
  builder:
    build: .
    platform: linux/amd64
    ports:
      - "8000:8000"
    volumes:
      - downloads:/app/downloads
      - pio_cache:/pio-home

volumes:
  downloads:
  pio_cache:
